# This docker-compose file is for dev purposes and it fires 5 core DroneGuard services:
# - DroneGuard Main Server (/DroneGuard/debriefing-service/server)
# - DroneGuard DB [mongoDB]
# - DroneGuard Control Server (/DroneGuard/control-server)
# - DroneGuard Main App (/DroneGuard/droneguard-app)
# - DroneGuard Debriefing App (/DroneGuard/debriefing-service/client/droneguard-debriefing)

version: '3.8'

services:
  dg_server:
    build: ./debriefing-service/server
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/droneguard
    depends_on:
      - 'mongo_db'

  mongo_db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - droneguard:/data/db

  debriefing_app:
    build: ./debriefing-service/client/droneguard-debriefing
    ports:
      - 3000:3000
    depends_on:
      - 'dg_server'

  control_server:
    build: ./control-server
    ports:
      - 3002:3002
    environment:
      DB_URL: mongodb://db/droneguard

  navigation_app:
    build: ./droneguard-app
    ports:
      - 3003:3003
    depends_on:
      - 'dg_server'

volumes:
  droneguard: