# All PRs and pushes trigger an automated process in which our unit tests and linter will run.
# If those succeed it's safe to merge the code into the master branch, otherwise, we should FIX the UTs 🍻

name: DroneGuard CI Workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  control-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: control-server

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run test:unit
    - run: npm run lint:validate

  droneguard-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debriefing-service/server

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run test:unit
    - run: npm run lint:validate