name: DroneGuard Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: control-server

    strategy:
      matrix:
        node-version: [10.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm i && npm test
